services:

  trellis2adc:
    build: .
    restart: 'unless-stopped'
    cap_add:
      - SYS_ADMIN
    volumes: 
      - .:/code
    working_dir: /code
    user: pptruser
    command: /code/entrypoint.sh
    environment:
      - ADC_USERNAME=${ADC_USERNAME}
      - ADC_PASSWORD=${ADC_PASSWORD}
      - OADA_DOMAIN=${OADA_DOMAIN}
      - OADA_TOKEN=${OADA_TOKEN}
      - SHOW_BROWSER=${SHOW_BROWSER:-false}
      - DEBUG=${DEBUG}
