services:

  trellis2adc:
    build: .
    restart: 'unless-stopped'
    volumes: 
      - .:/code
    working_dir: /code
    command: /code/entrypoint.sh
    environment:
      - ADC_USERNAME=${ADC_USERNAME}
      - ADC_PASSWORD=${ADC_PASSWORD}
      - OADA_DOMAIN=${OADA_DOMAIN}
      - OADA_TOKEN=${OADA_TOKEN}
      - DEBUG=${DEBUG}


# user: pptruser
# cap_add:
# - SYS_ADMIN

