services:

  trellis2adc:
    image: ghcr.io/puppeteer/puppeteer
    restart: 'unless-stopped'
    cap_add:
      - SYS_ADMIN
    volumes: 
      - .:/code
    working_dir: /code
    command: /code/entrypoint.sh
