services:

  trellis2adc:
    build: .
    restart: 'unless-stopped'
    cap_add:
      - SYS_ADMIN
    volumes: 
      - .:/code
    working_dir: /code
    user: pptruser
    command: /code/entrypoint.sh
